spring:
  # 配置数据源信息
  datasource:
  # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库信息
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/AS_PATH?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    url: jdbc:mysql://118.178.234.115:3306/AS_PATH?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: dcq16210

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:classpath:/com/*/*/mapper/**.xml